### ISSUE TITLE
Error: Mnemonic invalid or undefined

### ISSUE THREAD

**Issue by franswan** [PatrickAlphaC/chainlink_defi#4]
I've created an account at https://infura.io/ and made a project where under keys I've selected the kovan endpoint to use in the following commands:

``export MNEMONIC="apple, cheese, etc...."
export RPC_URL="https://kovan.infura.io/v3/adfdsfasdfadsfasdfadfadfadf"``

...replacing the RPC_URL with mine from Infura.

Now for the ``MNEMONIC``. I've just made up a string of words for this: (prevent indoor veteran upgrade salad limit prefer sausage december write giggle battle wisdom remind giant). 

I run:
``truffle migrate --network live --reset``

I get:
``Error: Mnemonic invalid or undefined
    at checkBIP39Mnemonic (/Users/User1/Desktop/chainlink_defi/node_modules/@truffle/hdwallet-provider/src/index.ts:79:15)
    at new HDWalletProvider (/Users/User1/Desktop/chainlink_defi/node_modules/@truffle/hdwallet-provider/src/index.ts:109:23)
    at Object.provider (/Users/User1/Desktop/chainlink_defi/truffle-config.js:14:16)
    at Object.getProvider (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:20:1)
    at Object.create (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:13:1)
    at TruffleConfig.get [as provider] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/configDefaults.js:204:1)
    at Object.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/environment/environment.js:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:206:1``

I am missing something obviously. Any idea?

**Comment by franswan** [comment]
I've figured it out. 

Helped in regard to mnemonic issue: https://www.trufflesuite.com/tutorials/using-infura-custom-provider

While my mnemonic was *defined*, it was really only *invalid*. I used the mnemonic generator referenced in the link above to swap out the one I was using and now it's working.

**Comment by PatrickAlphaC** [comment]
Aaaayyyyy - nice work :D
